import os
import subprocess
from urllib.parse import urlparse, urlunparse
from fastapi import FastAPI
from pydantic import BaseModel
from typing import Optional
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()

PORT = int(os.getenv("PORT", "9000"))
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")
GITHUB_REPO_URL = os.getenv("GITHUB_REPO_URL")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_BRANCH = os.getenv("GITHUB_BRANCH", "main")
GITHUB_COMMIT_NAME = os.getenv("GITHUB_COMMIT_NAME", "OpenAI Bot")
GITHUB_COMMIT_EMAIL = os.getenv("GITHUB_COMMIT_EMAIL", "bot@example.com")

if not OPENAI_API_KEY:
    raise RuntimeError("OPENAI_API_KEY must be set in the .env file")

client = OpenAI(api_key=OPENAI_API_KEY)
app = FastAPI(title="Telegram Webhook Receiver")


# Telegram sends nested JSON; we only need the text from message
class TelegramMessage(BaseModel):
    message_id: int
    text: Optional[str] = None


class TelegramUpdate(BaseModel):
    update_id: int
    message: Optional[TelegramMessage] = None


@app.get("/", include_in_schema=False)
@app.head("/", include_in_schema=False)
def root():
    return {"status": "ok"}


def _run_git_command(command, cwd):
    result = subprocess.run(command, cwd=cwd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip())
    return result.stdout.strip()


def _build_repo_remote_url(repo_url: str, token: Optional[str] = None) -> str:
    if not token or not repo_url.startswith("https://"):
        return repo_url

    parsed = urlparse(repo_url)
    netloc = f"x-access-token:{token}@{parsed.netloc}"
    return urlunparse(parsed._replace(netloc=netloc))


@app.post("/telegram/webhook")
def telegram_webhook(update: TelegramUpdate):
    text = update.message.text if update.message else None

    if not text:
        return {"ok": False, "error": "No message text provided"}

    response = client.responses.create(
        model=OPENAI_MODEL,
        input=[
            {
                "role": "system",
                "content": "You are a helpful assistant for a Telegram bot that can also help manage a GitHub repository.",
            },
            {"role": "user", "content": text},
        ],
    )

    reply = response.output_text

    if TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID:
        import requests

        requests.post(
            f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage",
            json={"chat_id": TELEGRAM_CHAT_ID, "text": reply},
            timeout=10,
        )

    if GITHUB_REPO_URL:
        repo_dir = os.path.join(os.getcwd(), "repo")
        os.makedirs(repo_dir, exist_ok=True)
        remote_url = _build_repo_remote_url(GITHUB_REPO_URL, GITHUB_TOKEN)

        if not os.path.exists(os.path.join(repo_dir, ".git")):
            _run_git_command(["git", "clone", remote_url, repo_dir], os.getcwd())
        else:
            _run_git_command(["git", "remote", "set-url", "origin", remote_url], repo_dir)

        try:
            _run_git_command(["git", "checkout", GITHUB_BRANCH], repo_dir)
        except RuntimeError:
            _run_git_command(["git", "checkout", "-b", GITHUB_BRANCH], repo_dir)

        with open(os.path.join(repo_dir, "README.md"), "a", encoding="utf-8") as f:
            f.write(f"\n<!-- Auto-generated by OpenAI bot at {os.getenv('PORT', '9000')} -->\n")

        _run_git_command(["git", "config", "user.name", GITHUB_COMMIT_NAME], repo_dir)
        _run_git_command(["git", "config", "user.email", GITHUB_COMMIT_EMAIL], repo_dir)
        _run_git_command(["git", "add", "README.md"], repo_dir)
        _run_git_command(["git", "commit", "-m", "Update from OpenAI bot"], repo_dir)
        _run_git_command(["git", "push", "origin", GITHUB_BRANCH], repo_dir)

    return {"ok": True, "reply": reply}


@app.get("/health")
def health():
    return {"status": "ok"}


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=PORT)
